/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Prefer environment variables for keys. Vite exposes env vars prefixed with VITE_.
const meta: any = typeof import.meta !== 'undefined' ? (import.meta as any) : {};

const _projectId = meta.env && meta.env.VITE_SUPABASE_PROJECT_ID
	? String(meta.env.VITE_SUPABASE_PROJECT_ID)
	: 'oufpkiwpnzjcbkojlirj';

const _publicAnonKey = meta.env && meta.env.VITE_SUPABASE_ANON_KEY
	? String(meta.env.VITE_SUPABASE_ANON_KEY)
	: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91ZnBraXdwbnpqY2Jrb2psaXJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyMzEwNTEsImV4cCI6MjA3NzgwNzA1MX0.-6UsC5kndFZxlyrKs60jlRHKL1MCDrSKJA5ivIEfHtQ';

export const projectId = _projectId;
export const publicAnonKey = _publicAnonKey;